<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Saran" failures="2" tests="4" name="Test" time="57.08" errors="0" timestamp="2025-05-15T21:45:53 IST">
  <testcase classname="testCases.TC_DatadrivenLoginTest" name="verifyLogin" time="13.116">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_DatadrivenLoginTest.verifyLogin(TC_DatadrivenLoginTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="testCases.TC_DatadrivenLoginTest" name="verifyLogin" time="11.93"/>
  <testcase classname="testCases.TC_DatadrivenLoginTest" name="verifyLogin" time="11.31">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testCases.TC_DatadrivenLoginTest.verifyLogin(TC_DatadrivenLoginTest.java:37)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyLogin -->
  <testcase classname="testCases.TC_DatadrivenLoginTest" name="verifyLogin" time="12.051"/>
</testsuite> <!-- Test -->
